version: '3.8'

services:
  globoclima-app:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
    container_name: globoclima-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    networks:
      - globoclima-network

  nginx:
    image: nginx:alpine
    container_name: globoclima-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - globoclima-app
    networks:
      - globoclima-network

networks:
  globoclima-network:
    driver: bridge